#!/bin/bash
#
# Build the phase 7 mockup kit (PRD §7.3).
#
# Concatenates exactly the stylesheets the Value Profile page loads, in the
# order Layouts/default.ctp loads them, and embeds the Font Awesome faces the
# page actually uses as data: URIs — the artifact CSP blocks every external
# host, so a mockup that links a font file gets no font at all.
#
# Output: prd/phase7/kit/mockup-kit.css
#
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
CSS="$ROOT/app/webroot/css"
FONTS="$ROOT/app/webroot/webfonts-fa7"
OUT="$ROOT/prd/phase7/kit/mockup-kit.css"

COMMIT=$(git -C "$ROOT" rev-parse --short HEAD)
DIRTY=""
if ! git -C "$ROOT" diff --quiet -- app/webroot/css; then
    DIRTY=" (working tree has uncommitted CSS changes)"
fi

python3 - "$CSS" "$FONTS" "$OUT" "$COMMIT" "$DIRTY" <<'PY'
import base64
import os
import re
import sys

css_dir, font_dir, out_path, commit, dirty = sys.argv[1:6]

# The order Layouts/default.ctp loads them, then the page's own sheet last.
# print.css is skipped: it loads at media="print" and says nothing about the
# screen.
SHEETS = [
    'bootstrap5-custom.min.css',
    'tom-select.bootstrap5.min.css',
    'mainOvermind.css',
    'fontawesome7.min.css',
    'misp-iconify.css',
    'value-profile.css',
]

# Font Awesome declares every face three times: once for the live family and
# twice more as "Font Awesome 5 Free" / "FontAwesome" aliases. Embedding on
# every occurrence would carry the same 112KB font three times over, so only
# the live family is embedded and the aliases are dropped — the page writes
# `fas fa-*` and `fa-solid`, which resolve to the FA7 family.
KEEP_FAMILY = 'Font Awesome 7 Free'
KEEP_FILES = ('fa-solid-900.woff2', 'fa-regular-400.woff2')

FACE = re.compile(r'@font-face\s*\{[^}]*\}')
FAMILY = re.compile(r'font-family:\s*"([^"]+)"')
SRC = re.compile(r'url\("\.\./webfonts-fa7/([a-z0-9.-]+\.woff2)"\)')

_cache = {}


def data_uri(name):
    if name not in _cache:
        with open(os.path.join(font_dir, name), 'rb') as handle:
            blob = base64.b64encode(handle.read()).decode('ascii')
        _cache[name] = 'data:font/woff2;base64,' + blob
    return _cache[name]


def rewrite_fonts(text):
    """Embed the faces the page uses; drop the aliases and the rest."""
    kept, dropped = [], []

    def handle(match):
        block = match.group(0)
        family = FAMILY.search(block)
        src = SRC.search(block)
        if not src:
            return block
        name = src.group(1)
        if family and family.group(1) == KEEP_FAMILY and name in KEEP_FILES:
            kept.append(name)
            return SRC.sub(lambda m: 'url("%s")' % data_uri(name), block)
        dropped.append('%s/%s' % (family.group(1) if family else '?', name))
        return ''

    return FACE.sub(handle, text), kept, dropped


chunks = [
    '/*\n'
    ' * Value Profile phase 7 — mockup kit.\n'
    ' *\n'
    ' * Generated by prd/phase7/kit/build-kit.sh. Do not edit by hand: it is\n'
    ' * a copy of MISP\'s own stylesheets, and hand-edits here become silent\n'
    ' * drift between the mockups and the page they are designing for.\n'
    ' *\n'
    ' * Source commit: %s%s\n'
    ' */\n' % (commit, dirty)
]

report = []
for sheet in SHEETS:
    # utf-8-sig, not utf-8: bootstrap5-custom.min.css opens with a BOM, and a
    # BOM landing mid-file after concatenation is an invalid token that takes
    # the rule after it down with it — which here is the whole :root block of
    # Bootstrap variables. Everything still parses; the colours just silently
    # stop resolving.
    with open(os.path.join(css_dir, sheet), encoding='utf-8-sig') as handle:
        text = handle.read()
    note = ''
    if sheet.startswith('fontawesome'):
        text, kept, dropped = rewrite_fonts(text)
        note = ' — embedded %s, dropped %d alias/unused faces' % (
            ', '.join(kept), len(dropped))
    chunks.append('\n/* ===== %s ===== */\n' % sheet)
    chunks.append(text)
    report.append('  %-32s %8.1f KB%s' % (sheet, len(text) / 1024.0, note))

blob = ''.join(chunks)
with open(out_path, 'w', encoding='utf-8') as handle:
    handle.write(blob)

print('\n'.join(report))
print('  %-32s %8.1f KB' % ('TOTAL', len(blob) / 1024.0))

# The kit is worthless if a sheet silently failed to carry its variables.
PROBES = ('--vp-mal', '--bs-primary', '.misp-icon', 'Font Awesome 7 Free',
          'data:font/woff2', 'data:image/svg+xml')
for probe in PROBES:
    if probe not in blob:
        raise SystemExit('!! kit is missing %s' % probe)
if 'webfonts-fa7' in blob:
    raise SystemExit('!! kit still references an external font file')
if '﻿' in blob:
    raise SystemExit('!! kit carries a BOM — the rule after it will be lost')
print('  probes ok: ' + ', '.join(PROBES))
PY

echo "wrote $OUT"
